version: '3'

services:
  db:
    image: postgres:13
    container_name: challenge-one-db-test
    restart: on-failure
    env_file:
      - .env
    expose:
      - 5432

  app:
    image: challenge-one
    container_name: challenge-one-app-test
    build:
      context: .
    command: 'python -m unittest discover -v .'
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env
