version: '3'

services:
  db:
    image: postgres:13
    container_name: challenge-one-db
    restart: on-failure
    env_file:
      - .env
    expose:
      - 5432

  app:
    image: challenge-one
    container_name: challenge-one-app
    build:
      context: .
    command: 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    restart: on-failure
    depends_on:
      - db
    ports:
      - 80:8000
    env_file:
      - .env
